### ISSUE TITLE
Expansion not a plugin

### ISSUE THREAD

**Issue by aBooDyy** [Zoon20X/LevelPointsPlacholders#1]
Hello there,

I've just checked your expansion in the [eCloud](https://api.extendedclip.com/expansions/levelpoints/) to verify it. You made a plugin and not an expansion, I have verified it because that won't effect its job as an expansion but that's not needed.
So `LPExpansions` class in this package `levelpointsplaceholders.levelpp` is not needed at all.

As i said, this won't effect its job as an expansion but just want to let you know.

Have a nice day!
aBooDyy

**Comment by Zoon20X** [comment]
i just removed the class, when i first worked on the expansion it kept throwing an error thats why it was there but thanks it's now removed

**Comment by aBooDyy** [comment]
You place this jar file in `plugins/PlaceholderAPI/expansions/` folder and not in the `plugins` folder.
Sorry i forgot to mention the `plugin.yml` file when i told you which class you should delete because you should've removed it too.
Its fine, you can remove the `plugin.yml` file later when you update the expansion and add new placeholders.
